### ISSUE TITLE
Remove Trailing Whitespaces from all Patch files

### ISSUE THREAD

**Issue by m0lese** [m0lese/portage-overlay#14]
# TODO
- [x] Check [runs/3123130355](https://github.com/m0lese/portage-overlay/runs/3123130355?check_suite_focus=true)
- [ ] Remove Trailing Whitespaces from the following files:
  - [ ] [prime/sys-kernel/ck-sources/files/0001-cpu-patches.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/ck-sources/files/0001-cpu-patches.patch)
  - [ ] [sys-kernel/vanilla-cacule/files/0001-cpu-patches.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/vanilla-cacule/files/0001-cpu-patches.patch)
  - [ ] [sys-kernel/vanilla-cacule/files/add-cacule-extraversion.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/vanilla-cacule/files/add-cacule-extraversion.patch)
  - [ ] [sys-kernel/vanilla-cacule/files/cacule-5.12.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/vanilla-cacule/files/cacule-5.12.patch)
  - [ ] [sys-kernel/vanilla-muqss/files/0001-MultiQueue-Skiplist-Scheduler-v0.210.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/vanilla-muqss/files/0001-MultiQueue-Skiplist-Scheduler-v0.210.patch)
  - [ ] [sys-kernel/vanilla-muqss/files/0001-cpu-patches.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/vanilla-muqss/files/0001-cpu-patches.patch)
  - [ ] [sys-kernel/vanilla-muqss/files/add-muqss-extraversion.patch](https://github.com/m0lese/portage-overlay/blob/prime/sys-kernel/vanilla-muqss/files/add-muqss-extraversion.patch)

**Comment by m0lese** [comment]
Not a good idea!
