### ISSUE TITLE
Add CI to sanity check ebuilds

### ISSUE THREAD

**Issue by m0lese** [m0lese/portage-overlay#3]
# TODO
- [x] Check [SpiderX/portage-ci/.../.travis.yml](https://github.com/SpiderX/portage-ci/blob/2315ca000497da3186afeed21a5a0361f56e24db/.travis.yml)
- [x] Check [mrueg/repoman-travis../.travis.yml](https://github.com/mrueg/repoman-travis/blob/master/.travis.yml)
- [x] Check [gentoo-mirror/guru/..../workflows/*.yml](https://github.com/gentoo-mirror/guru/tree/master/.github/workflows)

**Comment by m0lese** [comment]
Added: 08eb90e9eaaad154f31b83e96505ac6504f0f302, b1caace5fcdb68fc3411ba0aae086f8d3d661416, c0bfc36ed7acf6cb8ce39dd620b5724a33cd494f, f54f155f95c98a2df55b1fc49baa50b76f12c6fe
