### ISSUE TITLE
Bump all packages in sys-kernel

### ISSUE THREAD

**Issue by m0lese** [m0lese/portage-overlay#42]
### Branch 5.12

`5.12.19` is available upstream while local versions are `5.12.14`.

**Comment by m0lese** [comment]
## Todo
Bump the following (sys-kernel/)
- [ ] ck-sources (11991578d011c6673b1844bc88e557922aa6b212)
- [ ] vanilla-muqss (00248d77dd1546e4308623c384bd6dab8697880c)
- [ ] vanilla-cacule (5c34821ac7f8c16a3529fdb7ad609b5be52c39c9)
